const weekdayList = document.getElementById('weekdayList');
const imageFilesInput = document.getElementById('imageFiles');
const selectedFilesContainer = document.getElementById('selectedFiles');
const previewEl = document.getElementById('jsonPreview');
const ftpStatusEl = document.getElementById('ftpStatus');
const eventForm = document.getElementById('eventForm');
const referenceInput = eventForm.elements.reference;
const savedEventsList = document.getElementById('savedEventsList');
const savedEventsStatus = document.getElementById('savedEventsStatus');
let selectedFiles = [];
let savedEvents = [];
function sanitizeFileName(name) { return name.trim().replace(/\s+/g, '-').replace(/[^a-zA-Z0-9._-]/g, ''); }
function normalizeEuropeanTime(input) { const value=String(input||'').trim().replace('.',':'); if(!value)return ''; const match=/^(\d{1,2}):(\d{2})$/.exec(value); return match?`${match[1].padStart(2,'0')}:${match[2]}`:value; }
function parseDisplayDate(value){ const text=String(value||'').trim(); if(!text)return ''; const match=^(\d{1,2})/(\d{1,2})/(\d{4})$.exec(text); if(!match)return text; const [,d,m,y]=match; return `${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`; }
function formatDisplayDate(value){ const text=String(value||'').trim(); if(!text)return ''; const match=^(\d{4})-(\d{2})-(\d{2})$/.exec(text); if(!match)return text; const [,y,m,d]=match; return `${Number(d)}/${Number(m)}/${y}`; }
function addWeekdayRow(values={}) { const row=document.createElement('div'); row.className='weekday-row'; row.innerHTML=`<label>Day<input type="text" name="day" placeholder="Monday" value="${values.day||''}"></label><label>Time<input class="european-time" type="text" name="weekday_time" placeholder="HH:MM" value="${values.time||''}"></label><button type="button" class="remove-btn">Remove</button>`; row.querySelector('.remove-btn').addEventListener('click',()=>{row.remove();updatePreview();}); weekdayList.appendChild(row); }
function updateSelectedFilesList() { selectedFilesContainer.innerHTML=''; if(!selectedFiles.length){selectedFilesContainer.textContent='No new image attachments selected.';return;} selectedFiles.forEach(file=>{const pill=document.createElement('span');pill.className='file-pill';pill.textContent=file.name;selectedFilesContainer.appendChild(pill);}); }
function buildPayload() { const data=Object.fromEntries(new FormData(eventForm).entries()); data.time_start=normalizeEuropeanTime(data.time_start);data.time_end=normalizeEuropeanTime(data.time_end);data.date=parseDisplayDate(data.date);data.date_end=parseDisplayDate(data.date_end);data.category=Array.from(document.getElementById('category').selectedOptions).map(option=>Number(option.value));data.weekdays=Array.from(weekdayList.querySelectorAll('.weekday-row')).map(row=>({day:row.querySelector('[name="day"]').value,time:normalizeEuropeanTime(row.querySelector('[name="weekday_time"]').value)})).filter(item=>item.day||item.time);data.location_id='199';return {event:data,files:selectedFiles}; }
function updatePreview(){previewEl.textContent=JSON.stringify(buildPayload().event,null,2);}
function validateForm(){if(!eventForm.reportValidity())return false;const categories=document.getElementById('category').selectedOptions;if(!categories.length){document.getElementById('category').setCustomValidity('Select at least one category.');eventForm.reportValidity();document.getElementById('category').setCustomValidity('');return false;}if(!/^\d{2}:\d{2}$/.test(normalizeEuropeanTime(eventForm.elements.time_start.value))){eventForm.elements.time_start.setCustomValidity('Enter a valid time such as 19:30.');eventForm.reportValidity();eventForm.elements.time_start.setCustomValidity('');return false;}return true;}
function renderSavedEvents(){savedEventsList.innerHTML='';if(!savedEvents.length){savedEventsStatus.textContent='No saved events found.';return;}savedEventsStatus.textContent=`${savedEvents.length} saved event${savedEvents.length===1?'':'s'}. Click an event to edit it.`;savedEvents.forEach(event=>{const item=document.createElement('div');item.className='saved-event';const edit=document.createElement('button');edit.type='button';edit.className='saved-event-edit';edit.innerHTML='<strong></strong><span></span>';edit.querySelector('strong').textContent=event.title||'(untitled event)';edit.querySelector('span').textContent=event.date||'No date';edit.addEventListener('click',()=>loadEvent(event));const del=document.createElement('button');del.type='button';del.className='saved-event-delete';del.textContent='Delete';del.addEventListener('click',()=>deleteSavedEvent(event.reference));item.append(edit,del);savedEventsList.appendChild(item);});}
async function loadSavedEvents(){savedEventsStatus.textContent='Loading saved events...';try{const response=await fetch('/api/events');const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'Could not load saved events.');savedEvents=result.events||[];renderSavedEvents();}catch(error){savedEventsStatus.textContent=`Could not load saved events: ${error.message}`;}}
async function deleteSavedEvent(reference){if(!reference||!window.confirm(`Delete event ${reference}? This cannot be undone.`))return;try{const response=await fetch(`/api/events/${encodeURIComponent(reference)}`,{method:'DELETE'});const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'Delete failed.');if(referenceInput.value===reference)resetForm();ftpStatusEl.textContent=`Deleted ${reference}.`;await loadSavedEvents();}catch(error){ftpStatusEl.textContent=`Delete failed: ${error.message}`;}}
function loadEvent(event){if(event.date) eventForm.elements.date.value = formatDisplayDate(event.date); if(event.date_end) eventForm.elements.date_end.value = formatDisplayDate(event.date_end); Object.entries(event).forEach(([key,value])=>{const field=eventForm.elements[key];if(field&&!['category','weekdays','date','date_end'].includes(key))field.value=value==null?'':value;});document.querySelectorAll('#category option').forEach(option=>{option.selected=(event.category||[]).map(Number).includes(Number(option.value));});weekdayList.innerHTML='';(event.weekdays||[]).forEach(addWeekdayRow);if(!event.weekdays?.length)addWeekdayRow();selectedFiles=[];updateSelectedFilesList();updatePreview();ftpStatusEl.textContent=`Editing ${event.reference}. Upload to save changes.`;window.scrollTo({top:document.querySelector('.card-form').offsetTop-20,behavior:'smooth'});}
function filesAsBase64(){return Promise.all(selectedFiles.map(file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve({name:sanitizeFileName(file.name),base64:String(reader.result).split(',')[1]});reader.onerror=reject;reader.readAsDataURL(file);})));}
async function uploadToSftp(){if(!validateForm())return;ftpStatusEl.textContent='Uploading to SFTP server...';try{const payload=buildPayload();payload.files=await filesAsBase64();const response=await fetch('/api/upload',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'Upload failed.');ftpStatusEl.textContent=`Saved ${result.eventReference}.`;await loadSavedEvents();}catch(error){ftpStatusEl.textContent=`Upload failed: ${error.message}`;}}
function resetForm(){eventForm.reset();referenceInput.value='';weekdayList.innerHTML='';addWeekdayRow();selectedFiles=[];updateSelectedFilesList();updatePreview();ftpStatusEl.textContent='New event.';fetch('/api/reference',{method:'POST'}).then(response=>response.json()).then(result=>{if(result.ok)referenceInput.value=result.reference;}).catch(()=>{});}
imageFilesInput.addEventListener('change',event=>{selectedFiles=Array.from(event.target.files||[]);updateSelectedFilesList();updatePreview();});document.getElementById('addWeekdayBtn').addEventListener('click',()=>{addWeekdayRow();updatePreview();});document.getElementById('refreshEventsBtn').addEventListener('click',loadSavedEvents);document.getElementById('ftpUploadBtn').addEventListener('click',uploadToSftp);document.getElementById('resetBtn').addEventListener('click',resetForm);document.getElementById('previewBtn').addEventListener('click',()=>{if(validateForm())updatePreview();});eventForm.addEventListener('input',updatePreview);eventForm.addEventListener('change',updatePreview);addWeekdayRow();updateSelectedFilesList();updatePreview();loadSavedEvents();resetForm();
